// Builds src/styles/devicon/ with only the devicon glyphs referenced in src/.
// Run `pnpm icons` after adding or changing a `devicon-*` class.
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import subsetFont from 'subset-font';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = join(ROOT, 'src');
const DEVICON_DIR = join(ROOT, 'node_modules', 'devicon');
export const OUT_DIR = join(SRC_DIR, 'styles', 'devicon');
export const OUT_CSS = join(OUT_DIR, 'devicon-subset.css');
const OUT_FONT = join(OUT_DIR, 'devicon-subset.woff2');

const CLASS_PATTERN = /\bdevicon-[a-z0-9]+(?:-[a-z0-9]+)*/g;
// Only class names inside string literals (e.g. className="devicon-git-plain colored"), not paths like devicon/devicon-subset.css.
const SOURCE_CLASS_PATTERN = /(?<=["'`\s])devicon-[a-z0-9]+(?:-[a-z0-9]+)*(?=["'`\s])/g;

async function listSourceFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(entries.map((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return path === OUT_DIR ? [] : listSourceFiles(path);
    return /\.(jsx?|tsx?)$/.test(entry.name) ? [path] : [];
  }));
  return files.flat();
}

export async function findUsedDeviconClasses() {
  const used = new Set();
  for (const file of await listSourceFiles(SRC_DIR)) {
    const source = await readFile(file, 'utf8');
    source.match(SOURCE_CLASS_PATTERN)?.forEach((name) => used.add(name));
  }
  return used;
}

function parseRules(css) {
  return [...css.matchAll(/([^{}]+)\{([^{}]*)\}/g)].map(([, selectors, body]) => ({
    selectors: selectors.split(',').map((selector) => selector.trim()),
    body,
  }));
}

async function main() {
  const used = await findUsedDeviconClasses();
  const css = await readFile(join(DEVICON_DIR, 'devicon.min.css'), 'utf8');

  const glyphs = new Map();
  const colorRules = [];
  for (const { selectors, body } of parseRules(css)) {
    const kept = selectors.filter((selector) => {
      const classes = selector.match(CLASS_PATTERN);
      return classes && classes.every((name) => used.has(name));
    });
    if (kept.length === 0) continue;

    const content = body.match(/content:\s*"(.+?)"/u)?.[1];
    if (content) {
      kept.forEach((selector) => glyphs.set(selector.replace(/:before$/, ''), content));
    } else {
      colorRules.push(`${kept.join(',')}{${body}}`);
    }
  }

  const missing = [...used].filter((name) => !glyphs.has(`.${name}`));
  if (missing.length) throw new Error(`Unknown devicon classes: ${missing.join(', ')}`);

  const font = await readFile(join(DEVICON_DIR, 'fonts', 'devicon.ttf'));
  const subset = await subsetFont(font, [...new Set(glyphs.values())].join(''), { targetFormat: 'woff2' });

  const escape = (text) => [...text].map((char) => `\\${char.codePointAt(0).toString(16)}`).join('');
  const glyphRules = [...glyphs].sort(([a], [b]) => a.localeCompare(b))
    .map(([selector, content]) => `${selector}:before{content:"${escape(content)}"}`);

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_FONT, subset);
  await writeFile(OUT_CSS, [
    '/* Generated by scripts/subset-devicon.mjs (pnpm icons). Do not edit by hand. */',
    '@font-face{font-family:"devicon";src:url("./devicon-subset.woff2") format("woff2");font-weight:normal;font-style:normal;font-display:block}',
    '[class^=devicon-],[class*=" devicon-"]{font-family:"devicon" !important;speak:never;font-style:normal;font-weight:normal;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}',
    ...glyphRules,
    ...colorRules,
    '',
  ].join('\n'));

  console.log(`devicon subset: ${glyphs.size} icons, ${(subset.length / 1024).toFixed(1)} KB`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
